name: amplissimus
description: A good way of looking at Untis substitution plans using DSBMobile.

# Don't publish to pub.
publish_to: 'none'

# a.b.c+build_number
# Overridden in flutter build by --build-name and --build-number.
# Android: build-name = versionName, build-number = versionCode.
# https://developer.android.com/studio/publish/versioning
# iOS: build-name = CFBundleShortVersionString, build-number = CFBundleVersion.
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.0-1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.5
  crypto: ^3.0.0
  url_launcher: ^6.0.2
  dsbuntis: ^4.1.0
  schttp: ^3.1.0
  update: ^0.3.1
  html_search: ^0.1.1
  flutter_svg: ^0.21.0-nullsafety.0
  package_info: ^2.0.0
  touch_bar: ^0.1.0-alpha.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_tools:
    sdk: flutter
  #flutter_launcher_icons: ^0.8.1
  pedantic: ^1.11.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/logo.svg"

flutter:

  # Make sure that the Material Icons font is included.
  uses-material-design: true

  assets:
    - assets/logo.svg
    - assets/home.png
    - assets/settings.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # https://flutter.dev/custom-fonts/#from-packages
