# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # Removing this line breaks our versioning hacks
          fetch-depth: 0
      # Android needs Java
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      # Installs Flutter
      - uses: subosito/flutter-action@v1.4.0
      
      - run: echo ${{ secrets.ANDROID_KEY }} | base64 -d > ampdroid.jks
      - run: echo storePassword=${{ secrets.ANDROID_PASSPHRASE }} > android/key.properties
      - run: echo keyPassword=${{ secrets.ANDROID_PASSPHRASE }} >> android/key.properties
      - run: echo keyAlias=ampkey >> android/key.properties
      - run: echo storeFile=$PWD/ampdroid.jks >> android/key.properties

      - run: flutter pub get
      - run: flutter test

      - run: ./ci.sh ${{ secrets.GITHUB_TOKEN }} "$(mktemp -d)"
