name: CI

# Controls when the action will run. 
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0

      - run: flutter pub get
      - run: flutter test

  versions:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      short_version: ${{ steps.versions.outputs.short_version }}
      commit_count: ${{ steps.versions.outputs.commit_count }}
      version: ${{ steps.versions.outputs.version }}
    steps:
      - id: versions
        run: sh versions.sh

  build-mac:
    runs-on: macos-latest
    needs: versions
    env:
      short_version: ${{ needs.versions.outputs.short_version }}
      commit_count: ${{ needs.versions.outputs.commit_count }}
      version: ${{ needs.versions.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
      - run: ./make mac
      - uses: actions/upload-artifact@v2
        with:
          name: mac
          path: bin/

  build-ios:
    runs-on: macos-latest
    needs: versions
    env:
      short_version: ${{ needs.versions.outputs.short_version }}
      commit_count: ${{ needs.versions.outputs.commit_count }}
      version: ${{ needs.versions.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
      - run: ./make ios
      - uses: actions/upload-artifact@v2
        with:
          name: ios
          path: bin/

  build-windows:
    runs-on: windows-latest
    needs: versions
    env:
      short_version: ${{ needs.versions.outputs.short_version }}
      commit_count: ${{ needs.versions.outputs.commit_count }}
      version: ${{ needs.versions.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0

      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: dart run make.dart win

      - uses: actions/upload-artifact@v2
        with:
          name: win
          path: bin/

  build-linux:
    runs-on: ubuntu-latest
    needs: versions
    env:
      short_version: ${{ needs.versions.outputs.short_version }}
      commit_count: ${{ needs.versions.outputs.commit_count }}
      version: ${{ needs.versions.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: dev
      
      - run: ./make linux

      - uses: actions/upload-artifact@v2
        with:
          name: linux
          path: bin/

  build-android:
    runs-on: ubuntu-latest
    needs: versions
    env:
      short_version: ${{ needs.versions.outputs.short_version }}
      commit_count: ${{ needs.versions.outputs.commit_count }}
      version: ${{ needs.versions.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      # Android needs Java
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.4.0
      
      - run: echo ${{ secrets.ANDROID_KEY }} | base64 -d > ampdroid.jks
      - run: echo storePassword=${{ secrets.ANDROID_PASSPHRASE }} > android/key.properties
      - run: echo keyPassword=${{ secrets.ANDROID_PASSPHRASE }} >> android/key.properties
      - run: echo keyAlias=ampkey >> android/key.properties
      - run: echo storeFile=$PWD/ampdroid.jks >> android/key.properties

      - run: ./make android

      - uses: actions/upload-artifact@v2
        with:
          name: android
          path: bin/
