name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0

      - run: flutter pub get
      - run: flutter test

  versions:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      commit: ${{ steps.versions.outputs.commit }}
      short_version: ${{ steps.versions.outputs.short_version }}
      commit_count: ${{ steps.versions.outputs.commit_count }}
      version: ${{ steps.versions.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Allows our versioning hacks
      - id: versions
        run: ./versions.sh
  
  release:
    runs-on: ubuntu-latest
    needs: versions
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          bodyFile: "RELEASE.md"
          commit: ${{ needs.versions.outputs.commit }}
          prerelease: true
          tag: ${{ needs.versions.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest
    needs: release
    env:
      short_version: ${{ needs.versions.outputs.short_version }}
      commit_count: ${{ needs.versions.outputs.commit_count }}
      version: ${{ needs.versions.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
      - run: ./make mac
      - uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.versions.outputs.version }}
          args: "$(ls bin)"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/*"
          commit: ${{ needs.versions.outputs.commit }}
          tag: ${{ needs.versions.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-ios:
    runs-on: macos-latest
    needs: release
    env:
      short_version: ${{ needs.versions.outputs.short_version }}
      commit_count: ${{ needs.versions.outputs.commit_count }}
      version: ${{ needs.versions.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
      - run: ./make ios
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/*"
          commit: ${{ needs.versions.outputs.commit }}
          tag: ${{ needs.versions.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    needs: release
    env:
      short_version: ${{ needs.versions.outputs.short_version }}
      commit_count: ${{ needs.versions.outputs.commit_count }}
      version: ${{ needs.versions.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0

      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: dart run make.dart win

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/*"
          commit: ${{ needs.versions.outputs.commit }}
          tag: ${{ needs.versions.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    needs: release
    env:
      short_version: ${{ needs.versions.outputs.short_version }}
      commit_count: ${{ needs.versions.outputs.commit_count }}
      version: ${{ needs.versions.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: dev
      
      - run: ./make linux

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/*"
          commit: ${{ needs.versions.outputs.commit }}
          tag: ${{ needs.versions.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-android:
    runs-on: ubuntu-latest
    needs: release
    env:
      short_version: ${{ needs.versions.outputs.short_version }}
      commit_count: ${{ needs.versions.outputs.commit_count }}
      version: ${{ needs.versions.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.4.0
      
      - run: echo ${{ secrets.ANDROID_KEY }} | base64 -d > ampdroid.jks
      - run: echo storePassword=${{ secrets.ANDROID_PASSPHRASE }} > android/key.properties
      - run: echo keyPassword=${{ secrets.ANDROID_PASSPHRASE }} >> android/key.properties
      - run: echo keyAlias=ampkey >> android/key.properties
      - run: echo storeFile=$PWD/ampdroid.jks >> android/key.properties

      - run: ./make android

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/*"
          commit: ${{ needs.versions.outputs.commit }}
          tag: ${{ needs.versions.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
