name: CI

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.versions.outputs.commit }}
      short_version: ${{ steps.versions.outputs.short_version }}
      commit_count: ${{ steps.versions.outputs.commit_count }}
      version: ${{ steps.versions.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Allows our versioning hacks

      - uses: dart-lang/setup-dart@v1.0
      - id: versions
        run: dart run versions.dart

      - id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versions.outputs.version }}
          release_name: ${{ steps.versions.outputs.version }}
          body_path: RELEASE.md
          prerelease: true

  build-mac:
    runs-on: macos-latest
    needs: release
    env:
      short_version: ${{ needs.release.outputs.short_version }}
      commit_count: ${{ needs.release.outputs.commit_count }}
      version: ${{ needs.release.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
      - run: ./make mac
      - uses: Monorepo-Actions/setup-gh-cli@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: gh release upload ${{ needs.release.outputs.version }} bin/*

  build-ios:
    runs-on: macos-latest
    needs: release
    env:
      short_version: ${{ needs.release.outputs.short_version }}
      commit_count: ${{ needs.release.outputs.commit_count }}
      version: ${{ needs.release.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
      - run: ./make ios
      - uses: Monorepo-Actions/setup-gh-cli@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: gh release upload ${{ needs.release.outputs.version }} bin/*

  build-windows:
    runs-on: windows-latest
    needs: release
    env:
      short_version: ${{ needs.release.outputs.short_version }}
      commit_count: ${{ needs.release.outputs.commit_count }}
      version: ${{ needs.release.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0

      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: dart run make.dart win

      - uses: Monorepo-Actions/setup-gh-cli@v1.0.0
      - run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
      - run: gh release upload ${{ needs.release.outputs.version }} bin/amplissimus-${{ needs.release.outputs.version }}-windows-x86_64.zip

  build-linux:
    runs-on: ubuntu-latest
    container:
      image: appimagecrafters/appimage-builder:latest
    needs: release
    env:
      short_version: ${{ needs.release.outputs.short_version }}
      commit_count: ${{ needs.release.outputs.commit_count }}
      version: ${{ needs.release.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: beta

      - run: apt update
      - run: apt install -y clang cmake libgtk-3-dev ninja-build pkg-config git

      - run: ./make linux-x86_64

      - uses: Monorepo-Actions/setup-gh-cli@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: gh release upload ${{ needs.release.outputs.version }} bin/*

  build-android:
    runs-on: ubuntu-latest
    needs: release
    env:
      short_version: ${{ needs.release.outputs.short_version }}
      commit_count: ${{ needs.release.outputs.commit_count }}
      version: ${{ needs.release.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '12'
      - uses: subosito/flutter-action@v1.4.0

      - run: echo ${{ secrets.ANDROID_KEY }} | base64 -d > ampdroid.jks
      - run: echo storePassword=${{ secrets.ANDROID_PASSPHRASE }} > android/key.properties
      - run: echo keyPassword=${{ secrets.ANDROID_PASSPHRASE }} >> android/key.properties
      - run: echo keyAlias=ampkey >> android/key.properties
      - run: echo storeFile=$PWD/ampdroid.jks >> android/key.properties

      - run: ./make android

      - uses: Monorepo-Actions/setup-gh-cli@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: gh release upload ${{ needs.release.outputs.version }} bin/*
